// TODO: フェッチ処理を実装する
// reference: https://developer.themoviedb.org/reference/discover-movie
export const dummy_response_movies = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg",
      genre_ids: [10751, 35, 12, 14],
      id: 950387,
      original_language: "en",
      original_title: "A Minecraft Movie",
      overview:
        "謎のキューブ”の力で、マイクラワールドに転送された4人の仲間たち。そこは考えたモノを何でも作れる不思議な世界・・・だけど、夜になると四角いモンスターたちが襲いかかり、世界はとんでもないことに!? スティーブの力を借りて、4人はこの冒険をどうサバイバルするのか!?",
      popularity: 899.2165,
      poster_path: "/83bOe4KLTLMgtRXIGpd5ywTNbS6.jpg",
      release_date: "2025-03-31",
      title: "マインクラフト／ザ・ムービー",
      video: false,
      vote_average: 6.502,
      vote_count: 1274,
    },
    {
      adult: false,
      backdrop_path: "/j0NUh5irX7q2jIRtbLo8TZyRn6y.jpg",
      genre_ids: [27, 9648],
      id: 574475,
      original_language: "en",
      original_title: "Final Destination Bloodlines",
      overview: "",
      popularity: 503.2304,
      poster_path: "/6WxhEvFsauuACfv8HyoVX6mZKFj.jpg",
      release_date: "2025-05-09",
      title: "Final Destination Bloodlines",
      video: false,
      vote_average: 7.1,
      vote_count: 233,
    },
    {
      adult: false,
      backdrop_path: "/tyfO9jHgkhypUFizRVYD0bytPjP.jpg",
      genre_ids: [10751, 14],
      id: 447273,
      original_language: "en",
      original_title: "Snow White",
      overview: "",
      popularity: 375.4531,
      poster_path: "/8pJIDUkRwTW7N1AGOMGgWS3W9X0.jpg",
      release_date: "2025-03-12",
      title: "白雪姫",
      video: false,
      vote_average: 4.344,
      vote_count: 867,
    },
    {
      adult: false,
      backdrop_path: "/fTrQsdMS2MUw00RnzH0r3JWHhts.jpg",
      genre_ids: [28, 80, 53],
      id: 1197306,
      original_language: "en",
      original_title: "A Working Man",
      overview:
        "レヴォン・ケイドは、受勲もした軍歴を持つ極秘任務隊員だが、そのキャリアを封印し、建設業で質素な生活を送っていた。しかし、彼にとって家族同然である上司の娘が人身売買集団に連れ去られてしまう。彼女を連れ戻そうとするレヴォンは、捜索の過程で想像をはるかに上回る腐敗社会を目の当たりにするのだった。",
      popularity: 365.7532,
      poster_path: "/6FRFIogh3zFnVWn7Z6zcYnIbRcX.jpg",
      release_date: "2025-03-26",
      title: "ワーキング・マン",
      video: false,
      vote_average: 6.559,
      vote_count: 818,
    },
    {
      adult: false,
      backdrop_path: "/cJvUJEEQ86LSjl4gFLkYpdCJC96.jpg",
      genre_ids: [10752, 28],
      id: 1241436,
      original_language: "en",
      original_title: "Warfare",
      overview: "",
      popularity: 340.5692,
      poster_path: "/srj9rYrjefyWqkLc6l2xjTGeBGO.jpg",
      release_date: "2025-04-09",
      title: "Warfare",
      video: false,
      vote_average: 7.151,
      vote_count: 365,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 53],
      id: 1480799,
      original_language: "pt",
      original_title: "The Great Escape",
      overview: "",
      popularity: 364.4707,
      poster_path: "/h7shL668vhC2wsZQSBWzxkMuZ8K.jpg",
      release_date: "2023-05-26",
      title: "The Great Escape",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/jRvhP4AfFnJ03lCQhp1fie7XPSd.jpg",
      genre_ids: [28, 53],
      id: 977294,
      original_language: "en",
      original_title: "Tin Soldier",
      overview: "",
      popularity: 259.9182,
      poster_path: "/lFFDrFLXywFhy6khHes1LCFVMsL.jpg",
      release_date: "2025-05-22",
      title: "Tin Soldier",
      video: false,
      vote_average: 5.4,
      vote_count: 19,
    },
    {
      adult: false,
      backdrop_path: "/bIh56F8e5EaZ3r2nD1hXAOisItZ.jpg",
      genre_ids: [12, 10751],
      id: 1094473,
      original_language: "fr",
      original_title: "Bambi, l'histoire d'une vie dans les bois",
      overview: "",
      popularity: 249.7793,
      poster_path: "/nP7BaO9rObeav8SqcBcfcVoQN8g.jpg",
      release_date: "2024-10-16",
      title: "Bambi, l'histoire d'une vie dans les bois",
      video: false,
      vote_average: 6.053,
      vote_count: 19,
    },
    {
      adult: false,
      backdrop_path: "/rthMuZfFv4fqEU4JVbgSW9wQ8rs.jpg",
      genre_ids: [28, 878, 12],
      id: 986056,
      original_language: "en",
      original_title: "Thunderbolts*",
      overview:
        "軟禁、恫喝も厭わない――！？過去に様々な事情を抱えた彼らが、集められた目的とは…。超クセ者ヴィランチーム「サンダーボルツ*」。一筋縄ではいかない彼らが、世界中をまだ見ぬ興奮と熱狂の渦に巻き込む！",
      popularity: 195.4565,
      poster_path: "/aiNHyXJKw1DhQVHUIKZKmaoQTez.jpg",
      release_date: "2025-04-30",
      title: "サンダーボルツ*",
      video: false,
      vote_average: 7.47,
      vote_count: 912,
    },
    {
      adult: false,
      backdrop_path: "/4A5HH9HkCPqAwyYL6CnA0mxbYjn.jpg",
      genre_ids: [28, 80, 53, 18],
      id: 1144430,
      original_language: "fr",
      original_title: "Balle perdue 3",
      overview: "",
      popularity: 179.5989,
      poster_path: "/xccJs9vGCEvch1H9SIMSjNqrLKU.jpg",
      release_date: "2025-05-06",
      title: "Balle perdue 3",
      video: false,
      vote_average: 6.72,
      vote_count: 116,
    },
    {
      adult: false,
      backdrop_path: "/mrmaTVp7PTBkjj5G62cE9pjrENg.jpg",
      genre_ids: [27, 18],
      id: 1359977,
      original_language: "en",
      original_title: "Conjuring the Cult",
      overview: "",
      popularity: 175.3354,
      poster_path: "/t4MiAeYpjL7saYvqvcn9xtOfA4K.jpg",
      release_date: "2024-10-01",
      title: "Conjuring the Cult",
      video: false,
      vote_average: 5.727,
      vote_count: 22,
    },
    {
      adult: false,
      backdrop_path: "/jmLfuMFn6o4Rkp7dzT57Vp2GpoQ.jpg",
      genre_ids: [28, 18, 35],
      id: 897160,
      original_language: "ko",
      original_title: "용감한 시민",
      overview: "",
      popularity: 178.6921,
      poster_path: "/oVJDtwC41sGx5zmWiEkhqwBlopD.jpg",
      release_date: "2023-10-25",
      title: "勇敢な市民",
      video: false,
      vote_average: 7.053,
      vote_count: 38,
    },
    {
      adult: false,
      backdrop_path: "/bVm6udIB6iKsRqgMdQh6HywuEBj.jpg",
      genre_ids: [53, 28],
      id: 1233069,
      original_language: "de",
      original_title: "Exterritorial",
      overview:
        "アメリカ領事館の中で息子が姿を消した。我が子を探し出すために全力を尽くす特殊部隊の元兵士サラ。そうして捜索を続けるうちに、恐ろしい陰謀が明らかになってゆく。",
      popularity: 176.2712,
      poster_path: "/wqllCospPViEt7AeYIl4ZskKdSj.jpg",
      release_date: "2025-04-29",
      title: "エクステリトリアル",
      video: false,
      vote_average: 6.651,
      vote_count: 350,
    },
    {
      adult: false,
      backdrop_path: "/7ONMDhnErvpkKvkZqM82ud7bzcT.jpg",
      genre_ids: [28, 12, 53],
      id: 575265,
      original_language: "en",
      original_title: "Mission: Impossible - The Final Reckoning",
      overview: "",
      popularity: 205.7232,
      poster_path: "/aifqaY5TcsI2Lw2Shfsonk1w85w.jpg",
      release_date: "2025-05-17",
      title: "ミッション：インポッシブル／ファイナル・レコニング",
      video: false,
      vote_average: 7.554,
      vote_count: 74,
    },
    {
      adult: false,
      backdrop_path: "/aX5xxdrmf56jaD5VWs9HCWmrPc2.jpg",
      genre_ids: [27, 53],
      id: 1092073,
      original_language: "en",
      original_title: "The Haunting at Saint Joseph's",
      overview: "",
      popularity: 168.7271,
      poster_path: "/eDzQFxs0KTzHUPkIR0c44TSGJUR.jpg",
      release_date: "2023-02-26",
      title: "The Haunting at Saint Joseph's",
      video: false,
      vote_average: 4.444,
      vote_count: 9,
    },
    {
      adult: false,
      backdrop_path: "/8eifdha9GQeZAkexgtD45546XKx.jpg",
      genre_ids: [28, 53, 878],
      id: 822119,
      original_language: "en",
      original_title: "Captain America: Brave New World",
      overview:
        "“初代”キャプテン・アメリカことスティーブ・ロジャースから最も信頼され、盾を託されたファルコンことサム・ウィルソンは、その後、重圧と葛藤しながら“二代目”を受け入れる心を決めた。これまでアベンジャーズの中心人物としてリーダーシップを発揮してきた“キャプテン・アメリカ”は、単なるひとりのヒーローに留まらず、アメリカの象徴でもあり、さらにはヒーローの象徴とさえ言える存在だった。“ヒーローの象徴”キャプテン・アメリカを受け継いだ男の物語がここから始まる。",
      popularity: 136.0183,
      poster_path: "/vHkhLWb0M1ieP03WmQMjd8gAHxg.jpg",
      release_date: "2025-02-12",
      title: "キャプテン・アメリカ：ブレイブ・ニュー・ワールド",
      video: false,
      vote_average: 6.121,
      vote_count: 1863,
    },
    {
      adult: false,
      backdrop_path: "/op3qmNhvwEvyT7UFyPbIfQmKriB.jpg",
      genre_ids: [28, 14, 12],
      id: 324544,
      original_language: "en",
      original_title: "In the Lost Lands",
      overview: "",
      popularity: 141.3553,
      poster_path: "/dDlfjR7gllmr8HTeN6rfrYhTdwX.jpg",
      release_date: "2025-02-27",
      title: "In the Lost Lands",
      video: false,
      vote_average: 6.339,
      vote_count: 375,
    },
    {
      adult: false,
      backdrop_path: "/12tEzU0bNYKIjXXEwI5abuOotHF.jpg",
      genre_ids: [37],
      id: 710258,
      original_language: "en",
      original_title: "Rust",
      overview: "",
      popularity: 129.201,
      poster_path: "/tbJ3RkA2s6X5qrBzrYHYTxvDBui.jpg",
      release_date: "2025-05-01",
      title: "Rust",
      video: false,
      vote_average: 6.38,
      vote_count: 50,
    },
    {
      adult: false,
      backdrop_path: "/3MA11b8nXMEI29MGHIeFfp14YdN.jpg",
      genre_ids: [53, 878, 27],
      id: 1180763,
      original_language: "en",
      original_title: "From the Shadows",
      overview: "",
      popularity: 133.6326,
      poster_path: "/22aFuf6UnDaGP9G5CLfF92Cj1nf.jpg",
      release_date: "2023-09-22",
      title: "From the Shadows",
      video: false,
      vote_average: 3.1,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: "/nAxGnGHOsfzufThz20zgmRwKur3.jpg",
      genre_ids: [27, 53],
      id: 1233413,
      original_language: "en",
      original_title: "Sinners",
      overview: "",
      popularity: 121.6356,
      poster_path: "/jYfMTSiFFK7ffbY2lay4zyvTkEk.jpg",
      release_date: "2025-04-16",
      title: "Sinners",
      video: false,
      vote_average: 7.569,
      vote_count: 730,
    },
  ],
  total_pages: 50428,
  total_results: 1008542,
};
